### PR TITLE
review complete...!

### PR DESCRIPTION
**Pull request by abhishekpatel946**
# Change in code

- correct the date format

# Feature requested

- commented for improving your script or bug-free
- please read all the comments. 

##  NOTE
*Please read all the comments. I already suggested all the changes you need to change if any module or explain what portion of the code I changed or why?*

### CODE REVIEW

**Comment by gabywald** [comment]
Thnaks a lot : I'll review that as soon as possible to integrate the changes.

**Review by gabywald — COMMENTED** [review]
Which end-of-line convention do you use ?

**Comment by gabywald** [comment]
Following and continuing discussion on the Issue : https://github.com/gabywald/CurriculumGenerator/issues/39

**Comment by abhishekpatel946** [comment]
> Which end-of-line convention do you use ?
> (on my side is UNIX convention as '\n' only)

Mostly I write my code is vscode editor and I also '\n' for end of line.🙂
Is there any problem 🤔 Related to end of line?

**Comment by gabywald** [comment]
Just for checking '\n' and indentations ;-)

**Pull request closed without merging**
